require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# TODO: Remove before v1.0!
Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/BlockNesting:
  Max: 100

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 200

Style/ClassVars:
  Enabled: false
