name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rubocop

  test:
    name: "Test / Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        rails: ["7.0", "7.1", "7.2"]
        exclude:
          - ruby: "3.0"
            rails: "7.2"  # Rails 7.2 requires Ruby 3.1+
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set gemfile ${GITHUB_WORKSPACE}/gemfiles/rails_${{ matrix.rails }}.gemfile
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake test
