name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - run: bundle exec rubocop

  test:
    name: "Test / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set Gemfile
        run: |
          if [ "${{ matrix.ruby }}" = "3.0" ]; then
            echo "BUNDLE_GEMFILE=gemfiles/ruby_3_0.gemfile" >> $GITHUB_ENV
          else
            echo "BUNDLE_GEMFILE=gemfiles/ruby_3_1_plus.gemfile" >> $GITHUB_ENV
          fi
      - name: Install dependencies
        run: bundle install
      - run: bundle exec rake test

