name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"  # Use the lowest supported version for linting
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    name: "Test / Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: "3.0"
            gemfile: "ruby_3_0.gemfile"
          - ruby: "3.1"
            gemfile: "ruby_3_1_plus.gemfile"
          - ruby: "3.2"
            gemfile: "ruby_3_1_plus.gemfile"
          - ruby: "3.3"
            gemfile: "ruby_3_1_plus.gemfile"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
        run: |
          rm -f Gemfile.lock
          bundle install --jobs 4 --retry 3
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}
        run: bundle exec rake test